version: '3'

networks:
  fbk:

services:
  app:
    build: .
    networks:
      - fbk

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: fbk
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      fbk:
        aliases:
          - postgrya

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - fbk
